### ISSUE TITLE
Problems in Windows 10

### ISSUE THREAD

**Issue by jacuesta** [bluestreak01/questdb#52]
Hi, i would like to see the possible use of this library in our programs.
I've got a problem as I run the examples provided.

Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\Usuario\AppData\Local\Temp\libquestdb3846739714947417735.dll: %1 no es una aplicación Win32 válida

Both the Os and the JDK are 64bits. I reckon the origin of the error is that. Could you provide us a 64 bit version of the dll. 

Thanks in advance
Juan

**Comment by bluestreak01** [comment]
Hi Juan,

the DDL is 64bit bit already. It is compiled on Windows XP though, i'll have to check on windows 10 and get back to you.

Regards,
Vlad

**Comment by bluestreak01** [comment]
the error reads a bit suspicious though, DLL is indeed not a win32 application.

**Comment by bluestreak01** [comment]
Another idea: do you have anti-virus running and could be preventing java from accessing DLL?

**Comment by jacuesta** [comment]
Yes, i've got mcaffy running. I will try stopping it and let you know.
Thanks.

**Comment by jacuesta** [comment]
Hi Vlad,
It was my mystake. I did a save as with the right mouse button on the link and I didn't realize the file was not a dll one.

In order to be able to run the examples in a Windows platform I had to modify the Os.java 

                if (type == LINUX){
                    tempLib = File.createTempFile(lib, ".so");
                }else if (type == OSX){
                    tempLib = File.createTempFile(lib, ".dylib");
                }else if (type == WINDOWS){
                    tempLib = File.createTempFile(lib, ".dll");
                }

I'll carry on testing the library.

Regards,
Juan

**Comment by bluestreak01** [comment]
great, thanks Juan
