### ISSUE TITLE
Problems loading 7M real data

### ISSUE THREAD

**Issue by jacuesta** [bluestreak01/questdb#53]
Hi Vlad, as i told you I'm just in the middle of testing questdb. I want to test it with real data, I mean data we use in our current business.

In our case we've got a Oracle Database with 7/8 millions of bills. I've got a java program that extracts the data from the Oracle DB and writes the information in two different desatinations; a csv file and a questDB storage.

I'm using a modified version program that i'm beeen using to test other different libraries. The program uses sql2o to gather data from the relational DB and SimpleFlatMapper to generate the CSV file with the data. There is not any problem to generate the CSV file with the 8M of records.

But the problem comes up as I try to store the data in questDB. I get the error below. I've repeated the execution several times and the error appears,more or less, with the same number of bills loaded.

In attach, you'll find the java programs i've written.

[f.zip](https://github.com/bluestreak01/questdb/files/335644/f.zip)
[model.zip](https://github.com/bluestreak01/questdb/files/335647/model.zip)

un 27, 2016 8:24:07 PM jac.f readAndFlushAllFactura
INFORMACIÓN: .. y en el CSV
jun 27, 2016 8:24:07 PM jac.f readAndFlushAllFactura
INFORMACIÓN: .. y en questDB
jun 27, 2016 8:24:19 PM jac.f readAndFlushAllFactura
INFORMACIÓN: Recuperados 850000 registros de Facturas
jun 27, 2016 8:24:20 PM jac.f readAndFlushAllFactura
INFORMACIÓN: .. y en el CSV
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000002c99667, pid=12972, tid=15236
#
# JRE version: Java(TM) SE Runtime Environment (8.0_91-b15) (build 1.8.0_91-b15)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.91-b15 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# J 1965 C2 com.questdb.Partition.append(Ljava/lang/Object;)V (402 bytes) @ 0x0000000002c99667 [0x0000000002c99460+0x207]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# D:\JAC\Dropbox\des\Viesgo\questdb\hs_err_pid12972.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

Process finished with exit code 1

**Comment by bluestreak01** [comment]
Hi Juan, 

Your code looks ok, runs fine for me. I ran it for 10m of random strings - all ok. Questdb works only with primitive types, it would be skipping Double fields. If you have public data i can reproduce with i would appreciate it.

If you can export CSV file there is UI to load it up you can try.

- Run this main class: com.questdb.BootstrapMain, parameter is path to empty directory.
- Open browser on 'http://localhost:9000'
- Click on Upload button (second from top on left panel)
- Drag your csv into browser 

<img width="1184" alt="screen shot 2016-06-27 at 22 29 53" src="https://cloud.githubusercontent.com/assets/7276403/16396555/30e9a1a4-3cb7-11e6-8e88-45cdd45be191.png">
 
If CSV has header row, it will name journal columns using it. Types are recognised automatically, but you can adjust manually and reload if you need.

Regards,
Vlad

**Comment by jacuesta** [comment]
I'm gonna try importing the CSV i've got. 
Running the BootstrapMain I  get the following error:

D:\JAC\Dropbox\des\Questdb\bin>CALL .\lcp.bat ..\lib\annotations-15.0.jar
QDB HTTP Server 3.0
Copyright (C) Appsicle 2014-2016, all rights reserved.

Exception in thread "main" java.lang.NullPointerException
        at com.questdb.BootstrapMain.extractSite(BootstrapMain.java:128)
        at com.questdb.BootstrapMain.main(BootstrapMain.java:68)
Presione una tecla para continuar . . .

Do i need install anything else? what's the "Site"?

Regarding the primitive types, this is the reason why i've only got several fields in questdb db ( int and String). The rest of fields (Double, Integer, Boolean and Dates) are skipped, aren't they?
If i changed the data type to the primitive ones they would be processed by the engine, correct?
I've got to see how to implement this. There is a problem with the Oracle database definition; some fileds allow NULL as a value. I'll see how to get by.

Regards,

Juan

**Comment by bluestreak01** [comment]
"Site" is a directory unde resources, this is web site content that is being served when you run bootstrap. Usually maven packages it up in a jar. You can also run this from ide.

**Comment by bluestreak01** [comment]
If it helps QuestDB interprets Double.NaN values as null.

**Comment by jacuesta** [comment]
A CVS File with 7878870 real bills was loaded with 1.5M errors in a INT field. I realized that it is possible to change the field definition and reload the file. Changing from INT to LONG everything was ok.
The header row and the first one look like the example below. In this case instead of using ; we are using | as file delimiter.

id_fatr|id_distribuidora_cne|id_comercializadora_cne|cups|contrato|num_factura|id_tipofactrec_cne|num_factura_rectificada|ticket_energetico|fecha_factura|fecha_grabacion|dir_suministro|municipio|documento|observaciones|id_tipofactper_cne|id_tipofactura_cne|id_tipoidentif_cne|cif|fecha_boe|modo_facturacion|validado|fecha_validado|fecha_envio_portal|documento_backup|fecha_firma|fecha_sappi|cod_solicitud|fecha_solicitud|tipo_moneda|fecha_valor|fecha_limite_pago|id_tarifa_cne|fecha_ini|fecha_fin|cupspm|num_meses|ind_at_med_bt|val_lec|val_atr_lec|ind_envio_csa|fecha_envio_csa|modo_control_potencia|total|saldo_factura|saldo_cobro|base_ie|coef_ie|pct_ie|ie|importe_alquileres|importe_intereses|base_ivaigic_n|pct_ivaigic_n|ivaigic_n|base_ivaigic_r|pct_ivaigic_r|ivaigic_r|base_ivaigic_n2|pct_ivaigic_n2|ivaigic_n2|base_ivaigic_r2|pct_ivaigic_r2|ivaigic_r2|fdesde_cch|fhasta_cch|ind_curvacarga|pvpc|id_envio_cumas|id_res_cumas|tipofactura|id_tarifa|fecha_ini_portal
35692563|0027|0644|ES0027123456789123GK0F|1000551687|0810030014177165|N|0810740000910954|V000105121686|2015-01-02 00:00:00|2015-01-03 03:00:06|NAVALIAS 9 39108 MOMPIA|39108|/20150103/0027.0644.F1.01.0810030014177165.V000105121686.xml|073227064401|1|01|NI|B39111111|2014-02-01 00:00:00||OK|2015-01-03 03:16:40|2015-01-03 03:36:28||2015-01-03 03:35:56|2015-01-03 03:39:37|073227064401|2015-01-02 00:00:00|02|2015-01-03 00:00:00|2015-01-23 00:00:00|001|2014-09-04 00:00:00|2014-12-04 00:00:00|ES0027123456789123GK0F|3.07|N|||1|2015-01-05 12:07:19|true|93.85|93.85|93.85|0.0|0.0|0.0|0.0|2.45|0.0|77.56|21.0|16.29|0.0|0.0|0.0|0.0|0.0|0.0|0.0|0.0|0.0|2014-09-04 00:00:00|2014-12-04 00:00:00|true|false||||176|
and so on (+7878869 rows)

Please, how can i use the SQl Console. I want to test the data and verify that everything is ok in the questDB

**Comment by jacuesta** [comment]
Dude, i've just finded out how to run sqls. I've got to tell you that this database doesn't run but flies at speed light. it blows my mind....

**Comment by jacuesta** [comment]
select cups,sum(total) from Factura.csv --> read in 2.207s 695,436 rows
select cups,count() from Factura.csv --> read in 1.777s 695,436 rows
select count() from Factura.csv --> 0.02s 1 rows (7878870 as result)
select sum(total) from Factura.csv --> read in 0.239s 1 rows

**Comment by bluestreak01** [comment]
hi Juan, thanks. SQL is still in development, but most things are there (search, grouping, joins - including asof join and subqueries). But i guess you discovered some of them :)

Is that possible to have your data under non-disclosure agreement to troubleshoot the crash you initially reported?

**Comment by bluestreak01** [comment]
data can be scrambled as long as it still causes crash...

**Comment by jacuesta** [comment]
The compressed file weights 537M.

**Comment by bluestreak01** [comment]
do you use "slack" messaging?

**Comment by bluestreak01** [comment]
i just uploaded 250MB file there no problem, i'm sure 537M should be ok too

**Comment by bluestreak01** [comment]
Juan, issue should be resolved now. Thanks for your help resolving this bug.

**Comment by bluestreak01** [comment]
Feel free to reopen in case this still is an issue
