### ISSUE TITLE
With index JVM crashes

### ISSUE THREAD

**Issue by charlesgregory** [bluestreak01/questdb#54]
I have been using QuestDB embedded in my program and I love its speed however when I tried to create a symbol column with indexing it crashes the JVM like so:

# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000006d7d15c0, pid=7512, tid=5912
#
# JRE version: Java(TM) SE Runtime Environment (8.0_45-b15) (build 1.8.0_45-b15)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.45-b02 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# V  [jvm.dll+0x2715c0]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\musta_000\Desktop\Test\hs_err_pid7512.log
Compiled method (nm)    2050  349     n 0       sun.misc.Unsafe::copyMemory (native)
 total in heap  [0x0000000002bd1ad0,0x0000000002bd1e50] = 896
 relocation     [0x0000000002bd1bf0,0x0000000002bd1c38] = 72
 main code      [0x0000000002bd1c40,0x0000000002bd1e50] = 528
Compiled method (c1)    2063  433       3       sun.misc.Unsafe::copyMemory (11 bytes)
 total in heap  [0x0000000002c07b10,0x0000000002c07f28] = 1048
 relocation     [0x0000000002c07c30,0x0000000002c07c70] = 64
 main code      [0x0000000002c07c80,0x0000000002c07e00] = 384
 stub code      [0x0000000002c07e00,0x0000000002c07ea8] = 168
 metadata       [0x0000000002c07ea8,0x0000000002c07eb0] = 8
 scopes data    [0x0000000002c07eb0,0x0000000002c07ee0] = 48
 scopes pcs     [0x0000000002c07ee0,0x0000000002c07f20] = 64
 dependencies   [0x0000000002c07f20,0x0000000002c07f28] = 8
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

I am able to append approximately 9,586,980 rows to the Journal before the crash. (using a test case as my data takes a while to generate) I have been messing around with the JournalConfigurationBuilder options to try an alleviate this to no avail.
My configuration build looks as such:
public static final JournalConfigurationBuilder CONFIG = new JournalConfigurationBuilder() {{
        $(Primers.class)
                .keyColumn("Cluster").txCountHint(100000000)
                .$sym("Cluster").index().size(60).valueCountHint(100000000).noCache()
        ;
    }};
Primers.class has these columns:
private long Sequence;
private String Strain;
private String Cluster;
private boolean Hairpin;

I been trying my hardest to figure it out but I only have a basic understanding of how questdb works. I personally think it is running out of space for either the index or the journal file but I'm not sure. I can post the hs_err_pid7512.log if necessary. Thank you for your time.

**Comment by bluestreak01** [comment]
Could you add openFileTTL option to your journal set to an hour or something large. Similar issue has already been reported so it is worth a try.

**Comment by jacuesta** [comment]
Hi, I had a similar problem. The solution that Vlad point out worked out for me.
You have to add this in your JournalConfigurationBuilder:
 public static final JournalConfigurationBuilder CONFIG = new JournalConfigurationBuilder() {{
        $(F.class)
                .keyColumn("idfatr")
                .txCountHint(10000000)
                **.openFileTTL(1,TimeUnit.DAYS)**
        ;
}};

**Comment by charlesgregory** [comment]
I changed the Configuration builder to look like this now:
$(Primers.class)
                .keyColumn("Cluster").txCountHint(100000000).openFileTTL(1,TimeUnit.DAYS)
                .$sym("Cluster").index().size(60).valueCountHint(100000000).noCache()

However the JVM still crashes. If it helps the crash logs always have this section in common:

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 337  sun.misc.Unsafe.copyMemory(Ljava/lang/Object;JLjava/lang/Object;JJ)V (0 bytes) @ 0x00000000031b5af2 [0x00000000031b5a80+0x72]
j  sun.misc.Unsafe.copyMemory(JJJ)V+7
j  com.questdb.store.KVIndex.tx()V+160
j  com.questdb.store.KVIndex.add(IJ)V+8
J 605 C2 com.questdb.Partition.append(Ljava/lang/Object;)V (402 bytes) @ 0x00000000032a6f0c [0x00000000032a67a0+0x76c]
J 608 C2 NFSDBManager.insertPrimer(JLjava/lang/String;Ljava/lang/String;ZJ)V (52 bytes) @ 0x000000000329fcc4 [0x000000000329fba0+0x124]
J 609% C2 TestNFSDB.main([Ljava/lang/String;)V (295 bytes) @ 0x00000000032a40d0 [0x00000000032a3f60+0x170]
j  Test.main([Ljava/lang/String;)V+128
j  Main.main([Ljava/lang/String;)V+64
v  ~StubRoutines::call_stub

**Comment by jacuesta** [comment]
How many journal.commit() cals do you have in your code? In my test case I had a lot of them. Reducing them was an other way to eliminate the error I had.
 In my test case I was inserting 9m of records and I had a commit() per record. With only a commit() at the end of the insert operation I got no error.

**Comment by bluestreak01** [comment]
@charlesgregory are you using bulkwriter? I can reproduce problem with that.

Crash aside, indexes are very inefficient execution large volume of transactions. As @jacuesta said, you can commit at the end.

**Comment by bluestreak01** [comment]
It would also be massively helpful if you could share your test case?

**Comment by charlesgregory** [comment]
Yeah I have been working with bulkwriter. Using the regular writer causes the program to run out of memory. However it appears @jacuesta 's suggestion has worked. When the program commits only a few times it runs smoothly. I was committing on every append. My test case was as follows:
JournalFactory db = new JournalFactory(CONFIG.build("NFSDB"));
JournalWriter<Primers> primerTable= db.bulkWriter(Primers.class);
for (int i = 0; i < 100000000; i++) {
            Primers primer = new Primers();
            primer.Sequence=1045728378578L;
            primer.Cluster="V";
            primer.Strain="Mycobacterium";
            primer.Hairpin=false;
            primerTable.append(primer);
            //primerTable.commit();
            count++;
            if(i%100000==0) {
                System.out.print("\r");
                System.out.print(count);
            }
        }

**Comment by charlesgregory** [comment]
And my CONFIG looked like this:
public static final JournalConfigurationBuilder CONFIG = new JournalConfigurationBuilder() {{
$(Primers.class)
.keyColumn("Cluster").txCountHint(100000000)
.$sym("Cluster").index().size(60).valueCountHint(100000000).noCache()
;
}};

**Comment by bluestreak01** [comment]
phew, thanks. I can reproduce with bulk writer very easily and will fix asap. I'm glad that final commit() worked out for you. Thanks a lot for your help.

**Comment by charlesgregory** [comment]
You're welcome thanks for the quick response!

**Comment by bluestreak01** [comment]
This problem is fixed.
