### ISSUE TITLE
Requesting homebrew formula for installation

### ISSUE THREAD

**Issue by aahmed-se** [bluestreak01/questdb#55]
Provide a homebrew package installer (http://brew.sh/index.html)

say 'brew install questdb' && 'brew service start questdb'  to bring up the webui on osx

**Comment by bluestreak01** [comment]
It is a good idea, i'll look into it

**Comment by aahmed-se** [comment]
I will find some time to write the formula , can you point me to a public url for tar/zip distribution , don't want to create a compile task.

**Comment by bluestreak01** [comment]
I would appreciate it, thanks!

Would you be able to use this URL: https://www.questdb.org/download/questdb-1.0.0-SNAPSHOT-20160926-1758-bin.tar.gz for the time being?

I guess best it to make a release?

**Comment by aahmed-se** [comment]
Should work , will test the formula over the weekend and write back

**Comment by bluestreak01** [comment]
opened pull request:
https://github.com/Homebrew/homebrew-core/pull/5870

**Comment by bluestreak01** [comment]
another pull request: https://github.com/Homebrew/homebrew-core/pull/5884

**Comment by bluestreak01** [comment]
Pull request merged.

brew update
brew install questdb

**Comment by aahmed-se** [comment]
Looks good.

**Comment by bluestreak01** [comment]
thanks!

If you use WebUI please leave me some feedback, good or bad. I want everybody to enjoy using QuestDB.

**Comment by aahmed-se** [comment]
It's good so far, could benefit from youtube video , starting with a brew installation and going over some complex query examples with narration.

**Comment by bluestreak01** [comment]
thanks a lot

this is what i'm actually working on, video tutorial and documentation.
