### ISSUE TITLE
display and search data with different timezone

### ISSUE THREAD

**Issue by mingfai** [bluestreak01/questdb#59]
is there a way to work with the data in a different time zone other than GMT time?

it seems the question may affect the following aspects
-  insert date with timezone, e.g. PostgreSQL has "timestamp with time zone" data type
- customize the web-based ui to display data in a different time zone, this part should be easy
- search/query data with time in a different time zone

**Comment by bluestreak01** [comment]
Some of the timezone functionality is already implemented

- DATE in QuestDB is always UTC
- it is possible to insert DATE programmatically, you have to convert whatever timezone you have to UTC
- it is possible to display DATE in any Java-supported timezone, for example

```SQL
select TO_CHAR(mydate, 'dd-MM-y HH:mm:ss.SSS Z', 'PDT') from mytable
```

- there is also TO_DATE function if you stored date as STRING and want to copy table and convert string to DATE. Date format can include time zone 'Z'. QuestDB will attempt to match time zone from text to list of known ones and produce UTC date from that.

```SQL
select TO_DATE('03/2017', 'MM/y') from dual
```

- it is _not_ possible right now to import custom time zone via Web UI. It is a matter of allowing you to specify what timezone you data is in and UI will do the conversion.

- Defaulting the whole of UI to display specific time zone is also possible
