### ISSUE TITLE
`questdb.sh start` fails under Java 9

### ISSUE THREAD

**Issue by apjanke** [bluestreak01/questdb#61]
I'm on macOS 10.13.3, with Java 9.0.4 installed.

Starting up Questdb 1.0.4 fails.

Looks like it's due to `questdb.sh` using a `-XX:+PrintGCApplicationStoppedTime` option that's no longer supported under Oracle's Java 9 JRE.

```
$ wget https://www.questdb.org/download/questdb-1.0.4-bin.tar.gz
--2018-02-12 07:03:03--  https://www.questdb.org/download/questdb-1.0.4-bin.tar.gz
Resolving www.questdb.org (www.questdb.org)... 104.28.24.7, 104.28.25.7, 2400:cb00:2048:1::681c:1907, ...
Connecting to www.questdb.org (www.questdb.org)|104.28.24.7|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2659295 (2.5M) [application/gzip]
Saving to: ‘questdb-1.0.4-bin.tar.gz’

questdb-1.0.4-bin.tar.gz      100%[=================================================>]   2.54M  2.43MB/s    in 1.0s

2018-02-12 07:03:05 (2.43 MB/s) - ‘questdb-1.0.4-bin.tar.gz’ saved [2659295/2659295]

[~/tmp]
$ tar xf questdb-1.0.4-bin.tar.gz
[~/tmp]
$ cd questdb-1.0.4
[ ~/tmp/questdb-1.0.4]
$ ./questdb.sh start

  ___                  _   ____  ____
 / _ \ _   _  ___  ___| |_|  _ \| __ )
| | | | | | |/ _ \/ __| __| | | |  _ \
| |_| | |_| |  __/\__ \ |_| |_| | |_) |
 \__\_\\__,_|\___||___/\__|____/|____/
                       www.questdb.org

Created QuestDB ROOT directory: /usr/local/var/questdb
Unrecognized VM option 'PrintGCApplicationStoppedTime'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
[~/tmp/questdb-1.0.4]
$ java -version
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
```

When I tried editing the startup script to get it working, these options were also unrecognized:
* `-XX:+PrintGCTimeStamps`
* `-XX:+PrintGCDateStamps`

**Comment by bluestreak01** [comment]
hi Andrew,

Thanks for your report! Unfortunately there is a plethora of compatibility issues between QuestDB and Java9. Long term Java9 support is coming up. Are you able to use Java8 in the mean time?

**Comment by apjanke** [comment]
Sure; I was just wondering if this was an easy fix.

I'm mostly looking in to this for Mac Homebrew, where QuestDB is [failing under Java 9](https://github.com/Homebrew/homebrew-core/issues/19696). I'll just make it have a hard dependency on specifically Java 8; no problem.

**Comment by bluestreak01** [comment]
Great, thanks!

Not an easy fix sadly. Oracle have restructured JDK, hid some classes and enforced modularity. There is QuestDB version on branch that supports Java9 but it wouldn't be worth your while. Java8 performance is just the same with fewer hacks.

I'm developing a new storage engine that does away with JDK library and will be organically compatible with Java9. It is also much faster and infinitely more fail safe. So its worth the wait i think.

**Comment by apjanke** [comment]
Cool.

One gotcha: the `questdb.sh` startup script in Questdb 1.0.4 detects Java on macOS using the version `"1.7+"`. On systems with both Java 1.8 and 9 installed, this will prefer Java 9 and still break.

```
function export_java {

    if [ "$JAVA_HOME" = "" -a -e /usr/libexec/java_home ]; then
        JAVA_HOME=$(/usr/libexec/java_home -v 1.7+)
    fi
```

I can hack around this in Homebrew easily enough. But maybe it's worth putting out a 1.0.5 bugfix release so non-Homebrew Mac users can run Questdb without modification?

Same issue with `master`, if Java 9 compatibility is really a problem. It's [looking for 1.8+](https://github.com/bluestreak01/questdb/blob/2997c672ae79063920bccf103babc0ed2425c439/core/src/main/bin/questdb.sh#L47-L49), not 1.8 exactly, so will prefer Java 9.

```
    if [ "$JAVA_HOME" = "" -a -e /usr/libexec/java_home ]; then
        JAVA_HOME=$(/usr/libexec/java_home -v 1.8+)
    fi 
```

I think you might want to look for just `"1.8"` there, not `"1.8+"`.

**Comment by bluestreak01** [comment]
You are absolutely right, thanks! I think I put 1.8+ before knowing whats coming! Will fix and re-release asap!

**Comment by apjanke** [comment]
Awesome. Thanks for your super-speedy response.

**Comment by apjanke** [comment]
> I think I put 1.8+ before knowing whats coming!

And boy, none of us knew what was coming.

**Comment by bluestreak01** [comment]
You are most welcome! Thanks for homebrew fix!
